add search on content list
open-orchestra/open-orchestra-mongo-libs pull request #66
Opened 2017-01-19 09:35 UTC by itkg-nanne

2017-01-19 10:11 UTC, alavieille requested changes

2017-01-19 10:11 UTC, alavieille commented on Pagination/MongoTrait/FilterTypeStrategy/Strategies/DateFilterStrategy.php
> +        if ($this->contextManager->getDefaultLocale() == 'en') {
and the other local which use the same syntax ?

2017-01-19 13:49 UTC, ngilain commented on Pagination/MongoTrait/FilterTrait.php
> +    protected function generateFieldFilter(PaginateFinderConfiguration $configuration, Stage $qa, array $searchTypes)
@itkg-nanne : should introduce plural form in the function name as many filters are generated

2017-01-19 15:40 UTC, veolys-nanne commented
update done @alavieille , @ngilain

2017-01-19 16:54 UTC, ngilain commented
:+1:

2017-01-23 08:58 UTC, alavieille requested changes

2017-01-23 08:58 UTC, alavieille commented on Pagination/MongoTrait/FilterTypeStrategy/Strategies/StringFilterStrategy.php
> +        return $type === 'text';
can you use const for this ?

2017-01-23 09:23 UTC, itkg-nanne commented
update done @alavieille

2017-01-23 13:57 UTC, alavieille approved these changes

2017-01-24 09:19 UTC, merged